.TH PBUILDER-CREATEALL "1" "April 2010" "3\.3" "User Commands"
.SH NAME
pbuilder-createall \- updates images for multiple pbuilders
.SH SYNOPSIS
.B pbuilder-createall [--help]
.SH DESCRIPTION
pbuilder\-createall updates all the images for \fBspbuilder\fR.
.SH FILES
.TP
\fB$HOME/.pbuilderrc\fR
Created/modified by pbuilder\-setup.
.SH AUTHORS
Written by Jean-Christophe Dubacq
.SH SEE ALSO
.BR "debify" "(1), "
.BR "pbuilder-module" "(1), "
.BR "pbuilder-setup" "(1), "
.BR "pbuilder-updateall" "(1), "
.BR "spbuilder" "(1), "
.BR "uploadchangestool" "(1)"
.SH COPYRIGHT
Copyright \(co 2010 Jean-Christophe Dubacq.
.PP
BSD License.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
