.TH RFTG "6" "January 2010" "0.6.1" "Games"
.SH NAME
rftg \- play Race for the Galaxy game
.SH SYNOPSIS
.B rftg
[\fI\-p players\fR]
[\fI\-e expansion_level\fR]
[\fI\-a\fR]
[\fI\-r random_seed\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Allows single-player games of the \fIRace for the Galaxy\fR card game by
Rio Grande Games.
.SH OPTIONS
.TP
\fB\-p players\fR
specify the number of players (3-6)
.TP
\fB\-e expansion_level\fR
specify the expansion in use (0-2)
.TP
\fB\-a\fR
use the advanced rules
.TP
\fB\-r random_seed\fR
use this number to initialize the pseudo-random number generator
.SH AUTHOR
Written by Keldon Jones.
.SH COPYRIGHT
Copyright \(co 2009-2010 Keldon Jones.
Copyright \(co 2007-2009 Rio Grande Games.
License GPL-2+
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
