.TH DPKG-SPEEDUP "8" "March 2010" "1\.5" "Maintenance Commands"
.SH NAME
dpkg-speedup \- speeds up dpkg
.SH SYNOPSIS
.B dpkg-speedup [--help]
.SH DESCRIPTION
dpkg\-speedup uses a collection of recipes to speed\-up dpkg operation.
Use it as root.
.SH AUTHORS
Written by Jean-Christophe Dubacq
.SH COPYRIGHT
Copyright \(co 2010 Jean-Christophe Dubacq.
.PP
BSD License.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
